// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cashflux/v1/cashflux.proto

package backendrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeviceId      string                 `protobuf:"bytes,8,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Workspace) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Workspace) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Workspace) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Workspace) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Workspace) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DatasetEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	GzippedJson   []byte                 `protobuf:"bytes,2,opt,name=gzipped_json,json=gzippedJson,proto3" json:"gzipped_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetEnvelope) Reset() {
	*x = DatasetEnvelope{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetEnvelope) ProtoMessage() {}

func (x *DatasetEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetEnvelope.ProtoReflect.Descriptor instead.
func (*DatasetEnvelope) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{1}
}

func (x *DatasetEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DatasetEnvelope) GetGzippedJson() []byte {
	if x != nil {
		return x.GzippedJson
	}
	return nil
}

type BlobRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{2}
}

func (x *BlobRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlobRef) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *BlobRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWorkspacesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDeleted bool                   `protobuf:"varint,1,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkspacesRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IfNoneMatch   string                 `protobuf:"bytes,2,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWorkspaceRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	NotModified   bool                   `protobuf:"varint,2,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Workspace     *Workspace             `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Dataset       []byte                 `protobuf:"bytes,5,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkspaceResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetWorkspaceResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *GetWorkspaceResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *GetWorkspaceResponse) GetDataset() []byte {
	if x != nil {
		return x.Dataset
	}
	return nil
}

type PutWorkspaceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Workspace       *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Dataset         []byte                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	ClientUpdatedAt string                 `protobuf:"bytes,3,opt,name=client_updated_at,json=clientUpdatedAt,proto3" json:"client_updated_at,omitempty"`
	Force           bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutWorkspaceRequest) Reset() {
	*x = PutWorkspaceRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWorkspaceRequest) ProtoMessage() {}

func (x *PutWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*PutWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{7}
}

func (x *PutWorkspaceRequest) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *PutWorkspaceRequest) GetDataset() []byte {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *PutWorkspaceRequest) GetClientUpdatedAt() string {
	if x != nil {
		return x.ClientUpdatedAt
	}
	return ""
}

func (x *PutWorkspaceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PutWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Workspace     *Workspace             `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Dataset       []byte                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWorkspaceResponse) Reset() {
	*x = PutWorkspaceResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWorkspaceResponse) ProtoMessage() {}

func (x *PutWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*PutWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{8}
}

func (x *PutWorkspaceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PutWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *PutWorkspaceResponse) GetDataset() []byte {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *PutWorkspaceResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PutWorkspaceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteWorkspaceRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DeleteWorkspaceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWorkspaceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type WatchWorkspacesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDeleted bool                   `protobuf:"varint,1,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchWorkspacesRequest) Reset() {
	*x = WatchWorkspacesRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkspacesRequest) ProtoMessage() {}

func (x *WatchWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{11}
}

func (x *WatchWorkspacesRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type WatchWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchWorkspacesResponse) Reset() {
	*x = WatchWorkspacesResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkspacesResponse) ProtoMessage() {}

func (x *WatchWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*WatchWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{12}
}

func (x *WatchWorkspacesResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type SetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyRequest) Reset() {
	*x = SetKeyRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyRequest) ProtoMessage() {}

func (x *SetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyRequest.ProtoReflect.Descriptor instead.
func (*SetKeyRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{13}
}

func (x *SetKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SetKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyResponse) Reset() {
	*x = SetKeyResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyResponse) ProtoMessage() {}

func (x *SetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyResponse.ProtoReflect.Descriptor instead.
func (*SetKeyResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{14}
}

func (x *SetKeyResponse) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *SetKeyResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{15}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{16}
}

func (x *ListModelsResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{17}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{18}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{19}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type VisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	UserText      string                 `protobuf:"bytes,3,opt,name=user_text,json=userText,proto3" json:"user_text,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Temperature   float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	SchemaName    string                 `protobuf:"bytes,6,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Schema        []byte                 `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisionRequest) Reset() {
	*x = VisionRequest{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionRequest) ProtoMessage() {}

func (x *VisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionRequest.ProtoReflect.Descriptor instead.
func (*VisionRequest) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{20}
}

func (x *VisionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VisionRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *VisionRequest) GetUserText() string {
	if x != nil {
		return x.UserText
	}
	return ""
}

func (x *VisionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *VisionRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *VisionRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *VisionRequest) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{21}
}

func (x *Completion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Completion) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type CompletionChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChunk) Reset() {
	*x = CompletionChunk{}
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChunk) ProtoMessage() {}

func (x *CompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cashflux_v1_cashflux_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChunk.ProtoReflect.Descriptor instead.
func (*CompletionChunk) Descriptor() ([]byte, []int) {
	return file_cashflux_v1_cashflux_proto_rawDescGZIP(), []int{22}
}

func (x *CompletionChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompletionChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_cashflux_v1_cashflux_proto protoreflect.FileDescriptor

const file_cashflux_v1_cashflux_proto_rawDesc = "" +
	"\n" +
	"\x1acashflux/v1/cashflux.proto\x12\vcashflux.v1\"\xc9\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tdevice_id\x18\b \x01(\tR\bdeviceId\"[\n" +
	"\x0fDatasetEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12!\n" +
	"\fgzipped_json\x18\x02 \x01(\fR\vgzippedJson\"Y\n" +
	"\aBlobRef\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"@\n" +
	"\x15ListWorkspacesRequest\x12'\n" +
	"\x0finclude_deleted\x18\x01 \x01(\bR\x0eincludeDeleted\"P\n" +
	"\x16ListWorkspacesResponse\x126\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x16.cashflux.v1.WorkspaceR\n" +
	"workspaces\"I\n" +
	"\x13GetWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rif_none_match\x18\x02 \x01(\tR\vifNoneMatch\"\xb3\x01\n" +
	"\x14GetWorkspaceResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\fnot_modified\x18\x02 \x01(\bR\vnotModified\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x124\n" +
	"\tworkspace\x18\x04 \x01(\v2\x16.cashflux.v1.WorkspaceR\tworkspace\x12\x18\n" +
	"\adataset\x18\x05 \x01(\fR\adataset\"\xa7\x01\n" +
	"\x13PutWorkspaceRequest\x124\n" +
	"\tworkspace\x18\x01 \x01(\v2\x16.cashflux.v1.WorkspaceR\tworkspace\x12\x18\n" +
	"\adataset\x18\x02 \x01(\fR\adataset\x12*\n" +
	"\x11client_updated_at\x18\x03 \x01(\tR\x0fclientUpdatedAt\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\xbb\x01\n" +
	"\x14PutWorkspaceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x124\n" +
	"\tworkspace\x18\x02 \x01(\v2\x16.cashflux.v1.WorkspaceR\tworkspace\x12\x18\n" +
	"\adataset\x18\x03 \x01(\fR\adataset\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"d\n" +
	"\x16DeleteWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"3\n" +
	"\x17DeleteWorkspaceResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"A\n" +
	"\x16WatchWorkspacesRequest\x12'\n" +
	"\x0finclude_deleted\x18\x01 \x01(\bR\x0eincludeDeleted\"O\n" +
	"\x17WatchWorkspacesResponse\x124\n" +
	"\tworkspace\x18\x01 \x01(\v2\x16.cashflux.v1.WorkspaceR\tworkspace\"=\n" +
	"\rSetKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"D\n" +
	"\x0eSetKeyResponse\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x13\n" +
	"\x11ListModelsRequest\",\n" +
	"\x12ListModelsResponse\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"w\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.cashflux.v1.MessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\"\xdf\x01\n" +
	"\rVisionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x1b\n" +
	"\tuser_text\x18\x03 \x01(\tR\buserText\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12\x1f\n" +
	"\vschema_name\x18\x06 \x01(\tR\n" +
	"schemaName\x12\x16\n" +
	"\x06schema\x18\a \x01(\fR\x06schema\"P\n" +
	"\n" +
	"Completion\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12(\n" +
	"\x05usage\x18\x02 \x01(\v2\x12.cashflux.v1.UsageR\x05usage\"i\n" +
	"\x0fCompletionChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12(\n" +
	"\x05usage\x18\x02 \x01(\v2\x12.cashflux.v1.UsageR\x05usage\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done2\xd0\x03\n" +
	"\vSyncService\x12Y\n" +
	"\x0eListWorkspaces\x12\".cashflux.v1.ListWorkspacesRequest\x1a#.cashflux.v1.ListWorkspacesResponse\x12S\n" +
	"\fGetWorkspace\x12 .cashflux.v1.GetWorkspaceRequest\x1a!.cashflux.v1.GetWorkspaceResponse\x12S\n" +
	"\fPutWorkspace\x12 .cashflux.v1.PutWorkspaceRequest\x1a!.cashflux.v1.PutWorkspaceResponse\x12\\\n" +
	"\x0fDeleteWorkspace\x12#.cashflux.v1.DeleteWorkspaceRequest\x1a$.cashflux.v1.DeleteWorkspaceResponse\x12^\n" +
	"\x0fWatchWorkspaces\x12#.cashflux.v1.WatchWorkspacesRequest\x1a$.cashflux.v1.WatchWorkspacesResponse0\x012\xab\x03\n" +
	"\tAIService\x12A\n" +
	"\x06SetKey\x12\x1a.cashflux.v1.SetKeyRequest\x1a\x1b.cashflux.v1.SetKeyResponse\x12M\n" +
	"\n" +
	"ListModels\x12\x1e.cashflux.v1.ListModelsRequest\x1a\x1f.cashflux.v1.ListModelsResponse\x129\n" +
	"\x04Chat\x12\x18.cashflux.v1.ChatRequest\x1a\x17.cashflux.v1.Completion\x12=\n" +
	"\x06Vision\x12\x1a.cashflux.v1.VisionRequest\x1a\x17.cashflux.v1.Completion\x12F\n" +
	"\n" +
	"ChatStream\x12\x18.cashflux.v1.ChatRequest\x1a\x1c.cashflux.v1.CompletionChunk0\x01\x12J\n" +
	"\fVisionStream\x12\x1a.cashflux.v1.VisionRequest\x1a\x1c.cashflux.v1.CompletionChunk0\x01BHZFgithub.com/monstercameron/CashFlux/internal/backendrpc/pb;backendrpcpbb\x06proto3"

var (
	file_cashflux_v1_cashflux_proto_rawDescOnce sync.Once
	file_cashflux_v1_cashflux_proto_rawDescData []byte
)

func file_cashflux_v1_cashflux_proto_rawDescGZIP() []byte {
	file_cashflux_v1_cashflux_proto_rawDescOnce.Do(func() {
		file_cashflux_v1_cashflux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashflux_v1_cashflux_proto_rawDesc), len(file_cashflux_v1_cashflux_proto_rawDesc)))
	})
	return file_cashflux_v1_cashflux_proto_rawDescData
}

var file_cashflux_v1_cashflux_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cashflux_v1_cashflux_proto_goTypes = []any{
	(*Workspace)(nil),               // 0: cashflux.v1.Workspace
	(*DatasetEnvelope)(nil),         // 1: cashflux.v1.DatasetEnvelope
	(*BlobRef)(nil),                 // 2: cashflux.v1.BlobRef
	(*ListWorkspacesRequest)(nil),   // 3: cashflux.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),  // 4: cashflux.v1.ListWorkspacesResponse
	(*GetWorkspaceRequest)(nil),     // 5: cashflux.v1.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),    // 6: cashflux.v1.GetWorkspaceResponse
	(*PutWorkspaceRequest)(nil),     // 7: cashflux.v1.PutWorkspaceRequest
	(*PutWorkspaceResponse)(nil),    // 8: cashflux.v1.PutWorkspaceResponse
	(*DeleteWorkspaceRequest)(nil),  // 9: cashflux.v1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil), // 10: cashflux.v1.DeleteWorkspaceResponse
	(*WatchWorkspacesRequest)(nil),  // 11: cashflux.v1.WatchWorkspacesRequest
	(*WatchWorkspacesResponse)(nil), // 12: cashflux.v1.WatchWorkspacesResponse
	(*SetKeyRequest)(nil),           // 13: cashflux.v1.SetKeyRequest
	(*SetKeyResponse)(nil),          // 14: cashflux.v1.SetKeyResponse
	(*ListModelsRequest)(nil),       // 15: cashflux.v1.ListModelsRequest
	(*ListModelsResponse)(nil),      // 16: cashflux.v1.ListModelsResponse
	(*Message)(nil),                 // 17: cashflux.v1.Message
	(*Usage)(nil),                   // 18: cashflux.v1.Usage
	(*ChatRequest)(nil),             // 19: cashflux.v1.ChatRequest
	(*VisionRequest)(nil),           // 20: cashflux.v1.VisionRequest
	(*Completion)(nil),              // 21: cashflux.v1.Completion
	(*CompletionChunk)(nil),         // 22: cashflux.v1.CompletionChunk
}
var file_cashflux_v1_cashflux_proto_depIdxs = []int32{
	0,  // 0: cashflux.v1.ListWorkspacesResponse.workspaces:type_name -> cashflux.v1.Workspace
	0,  // 1: cashflux.v1.GetWorkspaceResponse.workspace:type_name -> cashflux.v1.Workspace
	0,  // 2: cashflux.v1.PutWorkspaceRequest.workspace:type_name -> cashflux.v1.Workspace
	0,  // 3: cashflux.v1.PutWorkspaceResponse.workspace:type_name -> cashflux.v1.Workspace
	0,  // 4: cashflux.v1.WatchWorkspacesResponse.workspace:type_name -> cashflux.v1.Workspace
	17, // 5: cashflux.v1.ChatRequest.messages:type_name -> cashflux.v1.Message
	18, // 6: cashflux.v1.Completion.usage:type_name -> cashflux.v1.Usage
	18, // 7: cashflux.v1.CompletionChunk.usage:type_name -> cashflux.v1.Usage
	3,  // 8: cashflux.v1.SyncService.ListWorkspaces:input_type -> cashflux.v1.ListWorkspacesRequest
	5,  // 9: cashflux.v1.SyncService.GetWorkspace:input_type -> cashflux.v1.GetWorkspaceRequest
	7,  // 10: cashflux.v1.SyncService.PutWorkspace:input_type -> cashflux.v1.PutWorkspaceRequest
	9,  // 11: cashflux.v1.SyncService.DeleteWorkspace:input_type -> cashflux.v1.DeleteWorkspaceRequest
	11, // 12: cashflux.v1.SyncService.WatchWorkspaces:input_type -> cashflux.v1.WatchWorkspacesRequest
	13, // 13: cashflux.v1.AIService.SetKey:input_type -> cashflux.v1.SetKeyRequest
	15, // 14: cashflux.v1.AIService.ListModels:input_type -> cashflux.v1.ListModelsRequest
	19, // 15: cashflux.v1.AIService.Chat:input_type -> cashflux.v1.ChatRequest
	20, // 16: cashflux.v1.AIService.Vision:input_type -> cashflux.v1.VisionRequest
	19, // 17: cashflux.v1.AIService.ChatStream:input_type -> cashflux.v1.ChatRequest
	20, // 18: cashflux.v1.AIService.VisionStream:input_type -> cashflux.v1.VisionRequest
	4,  // 19: cashflux.v1.SyncService.ListWorkspaces:output_type -> cashflux.v1.ListWorkspacesResponse
	6,  // 20: cashflux.v1.SyncService.GetWorkspace:output_type -> cashflux.v1.GetWorkspaceResponse
	8,  // 21: cashflux.v1.SyncService.PutWorkspace:output_type -> cashflux.v1.PutWorkspaceResponse
	10, // 22: cashflux.v1.SyncService.DeleteWorkspace:output_type -> cashflux.v1.DeleteWorkspaceResponse
	12, // 23: cashflux.v1.SyncService.WatchWorkspaces:output_type -> cashflux.v1.WatchWorkspacesResponse
	14, // 24: cashflux.v1.AIService.SetKey:output_type -> cashflux.v1.SetKeyResponse
	16, // 25: cashflux.v1.AIService.ListModels:output_type -> cashflux.v1.ListModelsResponse
	21, // 26: cashflux.v1.AIService.Chat:output_type -> cashflux.v1.Completion
	21, // 27: cashflux.v1.AIService.Vision:output_type -> cashflux.v1.Completion
	22, // 28: cashflux.v1.AIService.ChatStream:output_type -> cashflux.v1.CompletionChunk
	22, // 29: cashflux.v1.AIService.VisionStream:output_type -> cashflux.v1.CompletionChunk
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cashflux_v1_cashflux_proto_init() }
func file_cashflux_v1_cashflux_proto_init() {
	if File_cashflux_v1_cashflux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashflux_v1_cashflux_proto_rawDesc), len(file_cashflux_v1_cashflux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cashflux_v1_cashflux_proto_goTypes,
		DependencyIndexes: file_cashflux_v1_cashflux_proto_depIdxs,
		MessageInfos:      file_cashflux_v1_cashflux_proto_msgTypes,
	}.Build()
	File_cashflux_v1_cashflux_proto = out.File
	file_cashflux_v1_cashflux_proto_goTypes = nil
	file_cashflux_v1_cashflux_proto_depIdxs = nil
}
