// SPDX-License-Identifier: MIT

package merchantdict

// table is the shipped merchant dictionary. Entries are hand-authored from
// common bank-descriptor knowledge — deliberately NOT imported from a scraped or
// licensed merchant dataset, so the table carries no third-party terms.
//
// Rules for editing:
//   - One merchant per line, canonical display name first.
//   - Name it as the merchant, never as the descriptor: "Trader Joe's", not
//     "TRADER JOE'S #453 QPS". Matching normalizes both sides.
//   - Do NOT add payment processors (Square, PayPal, Toast, Clover, DoorDash's
//     billing prefix). Those are stripped by payeealias before lookup; adding
//     them here would shadow the real merchant.
//   - Prefer the bucket the merchant MOSTLY sells. A hardware store that also
//     sells snacks is still CatHome. When a merchant is genuinely split
//     (Target, Walmart), pick the dominant bucket and let the user's own history
//     (C513) override it — history outranks the dictionary in catsuggest.
//   - Keep it US/UK-centric for now; the matcher is locale-agnostic but the data
//     is not, and pretending otherwise would produce confident wrong answers.
var table = []Entry{
	// --- Groceries -----------------------------------------------------------
	{"Trader Joe's", CatGroceries},
	{"Whole Foods", CatGroceries},
	{"Safeway", CatGroceries},
	{"Kroger", CatGroceries},
	{"Publix", CatGroceries},
	{"Albertsons", CatGroceries},
	{"Aldi", CatGroceries},
	{"Lidl", CatGroceries},
	{"Wegmans", CatGroceries},
	{"Sprouts", CatGroceries},
	{"H-E-B", CatGroceries},
	{"Meijer", CatGroceries},
	{"Giant Eagle", CatGroceries},
	{"Food Lion", CatGroceries},
	{"Winn-Dixie", CatGroceries},
	{"Stop & Shop", CatGroceries},
	{"Ralphs", CatGroceries},
	{"Vons", CatGroceries},
	{"Harris Teeter", CatGroceries},
	{"Fresh Market", CatGroceries},
	{"Sainsburys", CatGroceries},
	{"Tesco", CatGroceries},
	{"Morrisons", CatGroceries},
	{"Waitrose", CatGroceries},
	{"Asda", CatGroceries},
	{"Instacart", CatGroceries},
	{"Costco", CatGroceries},
	{"Sams Club", CatGroceries},
	{"BJs Wholesale", CatGroceries},

	// --- Coffee --------------------------------------------------------------
	{"Starbucks", CatCoffee},
	{"Blue Bottle", CatCoffee},
	{"Dunkin", CatCoffee},
	{"Peets Coffee", CatCoffee},
	{"Caribou Coffee", CatCoffee},
	{"Tim Hortons", CatCoffee},
	{"Costa Coffee", CatCoffee},
	{"Pret A Manger", CatCoffee},

	// --- Dining --------------------------------------------------------------
	{"Chipotle", CatDining},
	{"McDonalds", CatDining},
	{"Burger King", CatDining},
	{"Wendys", CatDining},
	{"Taco Bell", CatDining},
	{"Subway", CatDining},
	{"Chick-fil-A", CatDining},
	{"Popeyes", CatDining},
	{"KFC", CatDining},
	{"Panera", CatDining},
	{"Panda Express", CatDining},
	{"Five Guys", CatDining},
	{"Shake Shack", CatDining},
	{"In-N-Out", CatDining},
	{"Dominos", CatDining},
	{"Pizza Hut", CatDining},
	{"Papa Johns", CatDining},
	{"Olive Garden", CatDining},
	{"Applebees", CatDining},
	{"Chilis", CatDining},
	{"Cheesecake Factory", CatDining},
	{"Buffalo Wild Wings", CatDining},
	{"Wingstop", CatDining},
	{"Sweetgreen", CatDining},
	{"Nandos", CatDining},
	{"Wagamama", CatDining},
	{"DoorDash", CatDining},
	{"Uber Eats", CatDining},
	{"Grubhub", CatDining},
	{"Deliveroo", CatDining},
	{"Just Eat", CatDining},
	{"Seamless", CatDining},
	{"Postmates", CatDining},
	{"Caviar", CatDining},

	// --- Gas / fuel ----------------------------------------------------------
	{"Shell", CatGas},
	{"Chevron", CatGas},
	{"Exxon", CatGas},
	{"Mobil", CatGas},
	{"BP", CatGas},
	{"Texaco", CatGas},
	{"Sunoco", CatGas},
	{"Valero", CatGas},
	{"Marathon", CatGas},
	{"Speedway", CatGas},
	{"Circle K", CatGas},
	{"Wawa", CatGas},
	{"QuikTrip", CatGas},
	{"Sheetz", CatGas},
	{"Buc-ees", CatGas},
	{"Esso", CatGas},

	// --- Transport -----------------------------------------------------------
	{"Uber", CatTransport},
	{"Lyft", CatTransport},
	{"Amtrak", CatTransport},
	{"Greyhound", CatTransport},
	{"Zipcar", CatTransport},
	{"Lime", CatTransport},
	{"Bird", CatTransport},
	{"SpotHero", CatTransport},
	{"ParkMobile", CatTransport},
	{"E-ZPass", CatTransport},
	{"Transport for London", CatTransport},
	{"Trainline", CatTransport},
	{"Jiffy Lube", CatTransport},
	{"Discount Tire", CatTransport},
	{"AutoZone", CatTransport},
	{"OReilly Auto Parts", CatTransport},
	{"Advance Auto Parts", CatTransport},

	// --- Travel --------------------------------------------------------------
	{"Delta Air Lines", CatTravel},
	{"United Airlines", CatTravel},
	{"American Airlines", CatTravel},
	{"Southwest Airlines", CatTravel},
	{"Alaska Airlines", CatTravel},
	{"JetBlue", CatTravel},
	{"Frontier Airlines", CatTravel},
	{"British Airways", CatTravel},
	{"Ryanair", CatTravel},
	{"EasyJet", CatTravel},
	{"Airbnb", CatTravel},
	{"Vrbo", CatTravel},
	{"Booking.com", CatTravel},
	{"Expedia", CatTravel},
	{"Hotels.com", CatTravel},
	{"Marriott", CatTravel},
	{"Hilton", CatTravel},
	{"Hyatt", CatTravel},
	{"Holiday Inn", CatTravel},
	{"Travelodge", CatTravel},
	{"Premier Inn", CatTravel},

	// --- Shopping / general --------------------------------------------------
	{"Amazon", CatShopping},
	{"Target", CatShopping},
	{"Walmart", CatShopping},
	{"eBay", CatShopping},
	{"Etsy", CatShopping},
	{"AliExpress", CatShopping},
	{"Temu", CatShopping},
	{"Shein", CatShopping},
	{"Wayfair", CatHousehold},
	{"IKEA", CatHousehold},
	{"Bed Bath & Beyond", CatHousehold},
	{"Container Store", CatHousehold},
	{"Dollar General", CatHousehold},
	{"Dollar Tree", CatHousehold},
	{"Family Dollar", CatHousehold},
	{"Argos", CatHousehold},
	{"John Lewis", CatHousehold},

	// --- Home improvement ----------------------------------------------------
	{"Home Depot", CatHome},
	{"Lowes", CatHome},
	{"Ace Hardware", CatHome},
	{"Menards", CatHome},
	{"Sherwin-Williams", CatHome},
	{"B&Q", CatHome},
	{"Screwfix", CatHome},

	// --- Electronics ---------------------------------------------------------
	{"Best Buy", CatElectronics},
	{"Micro Center", CatElectronics},
	{"Newegg", CatElectronics},
	{"Apple Store", CatElectronics},
	{"Currys", CatElectronics},

	// --- Clothing ------------------------------------------------------------
	{"Nike", CatClothing},
	{"Adidas", CatClothing},
	{"Lululemon", CatClothing},
	{"Old Navy", CatClothing},
	{"Gap", CatClothing},
	{"Uniqlo", CatClothing},
	{"H&M", CatClothing},
	{"Zara", CatClothing},
	{"Nordstrom", CatClothing},
	{"Macys", CatClothing},
	{"Kohls", CatClothing},
	{"TJ Maxx", CatClothing},
	{"Marshalls", CatClothing},
	{"Ross Stores", CatClothing},
	{"Primark", CatClothing},
	{"Next Retail", CatClothing},
	{"Marks & Spencer", CatClothing},

	// --- Subscriptions / streaming -------------------------------------------
	{"Netflix", CatSubscriptions},
	{"Spotify", CatSubscriptions},
	{"Hulu", CatSubscriptions},
	{"Disney Plus", CatSubscriptions},
	{"HBO Max", CatSubscriptions},
	{"Max", CatSubscriptions},
	{"Paramount Plus", CatSubscriptions},
	{"Peacock", CatSubscriptions},
	{"Apple Music", CatSubscriptions},
	{"Apple TV", CatSubscriptions},
	{"YouTube Premium", CatSubscriptions},
	{"Audible", CatSubscriptions},
	{"Patreon", CatSubscriptions},
	{"Substack", CatSubscriptions},
	{"Dropbox", CatSubscriptions},
	{"Adobe", CatSubscriptions},
	{"Microsoft 365", CatSubscriptions},
	{"Google Storage", CatSubscriptions},
	{"iCloud", CatSubscriptions},
	{"OpenAI", CatSubscriptions},
	{"Anthropic", CatSubscriptions},
	{"GitHub", CatSubscriptions},
	{"Notion", CatSubscriptions},
	{"Canva", CatSubscriptions},
	{"LinkedIn Premium", CatSubscriptions},
	{"New York Times", CatSubscriptions},
	{"Washington Post", CatSubscriptions},
	{"Medium", CatSubscriptions},

	// --- Entertainment -------------------------------------------------------
	{"Steam", CatEntertainment},
	{"PlayStation", CatEntertainment},
	{"Xbox", CatEntertainment},
	{"Nintendo", CatEntertainment},
	{"Epic Games", CatEntertainment},
	{"Twitch", CatEntertainment},
	{"AMC Theatres", CatEntertainment},
	{"Regal Cinemas", CatEntertainment},
	{"Cinemark", CatEntertainment},
	{"Ticketmaster", CatEntertainment},
	{"StubHub", CatEntertainment},
	{"Eventbrite", CatEntertainment},
	{"Dave & Busters", CatEntertainment},
	{"Odeon", CatEntertainment},
	{"Vue Cinemas", CatEntertainment},

	// --- Health / pharmacy ---------------------------------------------------
	{"CVS", CatPharmacy},
	{"Walgreens", CatPharmacy},
	{"Rite Aid", CatPharmacy},
	{"Boots", CatPharmacy},
	{"GoodRx", CatPharmacy},
	{"Quest Diagnostics", CatHealth},
	{"LabCorp", CatHealth},
	{"Zocdoc", CatHealth},
	{"Warby Parker", CatHealth},
	{"LensCrafters", CatHealth},
	{"1-800 Contacts", CatHealth},

	// --- Fitness -------------------------------------------------------------
	{"Planet Fitness", CatFitness},
	{"LA Fitness", CatFitness},
	{"Equinox", CatFitness},
	{"Anytime Fitness", CatFitness},
	{"Gold's Gym", CatFitness},
	{"Crunch Fitness", CatFitness},
	{"ClassPass", CatFitness},
	{"Peloton", CatFitness},
	{"Strava", CatFitness},
	{"PureGym", CatFitness},

	// --- Utilities / telecoms ------------------------------------------------
	{"Comcast", CatInternet},
	{"Xfinity", CatInternet},
	{"Spectrum", CatInternet},
	{"Cox Communications", CatInternet},
	{"CenturyLink", CatInternet},
	{"Frontier Communications", CatInternet},
	{"Google Fiber", CatInternet},
	{"Starlink", CatInternet},
	{"BT Broadband", CatInternet},
	{"Virgin Media", CatInternet},
	{"Verizon", CatPhone},
	{"AT&T", CatPhone},
	{"T-Mobile", CatPhone},
	{"Mint Mobile", CatPhone},
	{"Cricket Wireless", CatPhone},
	{"Boost Mobile", CatPhone},
	{"Vodafone", CatPhone},
	{"EE Mobile", CatPhone},
	// Google Fi is the mobile carrier, distinct from Google Fiber (internet) two
	// entries above. Lookup tries longest key first, so "GOOGLE FIBER" still
	// resolves to Fiber and only a bare "GOOGLE FI" lands here (C691).
	{"Google Fi", CatPhone},
	{"Duke Energy", CatUtilities},
	{"Pacific Gas and Electric", CatUtilities},
	{"Con Edison", CatUtilities},
	{"National Grid", CatUtilities},
	{"Georgia Power", CatUtilities},
	{"Florida Power & Light", CatUtilities},
	// The descriptor a Florida bank actually prints is "FPL DIRECT DEBIT" or
	// "FPL ELECTRIC", never the spelled-out name above — so the spelled-out entry
	// alone never fires on a real statement. Short, but token-bounded matching
	// keeps it from firing inside a longer word (C691).
	{"FPL", CatUtilities},
	{"British Gas", CatUtilities},
	{"Octopus Energy", CatUtilities},
	{"Thames Water", CatUtilities},
	// Municipal water / waste / stormwater bills descriptor as the city itself.
	{"City of Lauderhill", CatUtilities},
	// Homeowners-association dues. Generic on purpose: the association's own name
	// varies per household and is unguessable, but "HOA" is in nearly every such
	// descriptor, and TypeUtilities already covers HOA dues as a service account.
	{"HOA", CatUtilities},

	// --- Insurance -----------------------------------------------------------
	{"Geico", CatInsurance},
	{"Progressive", CatInsurance},
	{"State Farm", CatInsurance},
	{"Allstate", CatInsurance},
	{"USAA", CatInsurance},
	{"Liberty Mutual", CatInsurance},
	{"Nationwide", CatInsurance},
	{"Aetna", CatInsurance},
	{"Cigna", CatInsurance},
	{"Blue Cross", CatInsurance},
	{"Admiral Insurance", CatInsurance},
	{"Aviva", CatInsurance},

	// --- Pets ----------------------------------------------------------------
	{"Chewy", CatPets},
	{"Petco", CatPets},
	{"PetSmart", CatPets},
	{"Pets at Home", CatPets},
	{"Rover", CatPets},

	// --- Kids ----------------------------------------------------------------
	{"Buy Buy Baby", CatKids},
	{"Carters", CatKids},
	{"Bright Horizons", CatKids},
	{"KinderCare", CatKids},

	// --- Education -----------------------------------------------------------
	{"Coursera", CatEducation},
	{"Udemy", CatEducation},
	{"Duolingo", CatEducation},
	{"Khan Academy", CatEducation},
	{"Chegg", CatEducation},
	{"Nelnet", CatEducation},
	{"Sallie Mae", CatEducation},

	// --- Charity -------------------------------------------------------------
	{"GoFundMe", CatCharity},
	{"Red Cross", CatCharity},
	{"UNICEF", CatCharity},
	{"Doctors Without Borders", CatCharity},
	{"St Jude", CatCharity},
	{"Wikimedia", CatCharity},

	// --- Bank fees -----------------------------------------------------------
	{"Overdraft Fee", CatFees},
	{"Monthly Maintenance Fee", CatFees},
	{"ATM Fee", CatFees},
	{"Foreign Transaction Fee", CatFees},
	{"Wire Transfer Fee", CatFees},
}
