// SPDX-License-Identifier: MIT

package styles

// Typed property constructors — one per CSS property the design system uses, so a
// property name is never a raw string at a rule call site. Each returns a decl.
// Migrated from the original stylesheet; now the canonical source, edit as Go.

func webkitAppearance(v string) decl        { return decl{"-webkit-appearance", v} }
func webkitBackdropFilter(v string) decl    { return decl{"-webkit-backdrop-filter", v} }
func webkitFontSmoothing(v string) decl     { return decl{"-webkit-font-smoothing", v} }
func webkitOverflowScrolling(v string) decl { return decl{"-webkit-overflow-scrolling", v} }
func accentColor(v string) decl             { return decl{"accent-color", v} }
func alignContent(v string) decl            { return decl{"align-content", v} }
func alignItems(v string) decl              { return decl{"align-items", v} }
func alignSelf(v string) decl               { return decl{"align-self", v} }
func animation(v string) decl               { return decl{"animation", v} }
func animationDelay(v string) decl          { return decl{"animation-delay", v} }
func appearance(v string) decl              { return decl{"appearance", v} }
func backdropFilter(v string) decl          { return decl{"backdrop-filter", v} }
func backfaceVisibility(v string) decl      { return decl{"backface-visibility", v} }
func background(v string) decl              { return decl{"background", v} }
func backgroundClip(v string) decl          { return decl{"background-clip", v} }
func backgroundColor(v string) decl         { return decl{"background-color", v} }
func backgroundImage(v string) decl         { return decl{"background-image", v} }
func backgroundPosition(v string) decl      { return decl{"background-position", v} }
func backgroundSize(v string) decl          { return decl{"background-size", v} }
func border(v string) decl                  { return decl{"border", v} }
func borderBottom(v string) decl            { return decl{"border-bottom", v} }
func borderBottomColor(v string) decl       { return decl{"border-bottom-color", v} }
func borderBottomWidth(v string) decl       { return decl{"border-bottom-width", v} }
func borderCollapse(v string) decl          { return decl{"border-collapse", v} }
func borderColor(v string) decl             { return decl{"border-color", v} }
func borderInline(v string) decl            { return decl{"border-inline", v} }
func borderLeft(v string) decl              { return decl{"border-left", v} }
func borderLeftColor(v string) decl         { return decl{"border-left-color", v} }
func borderRadius(v string) decl            { return decl{"border-radius", v} }
func borderRight(v string) decl             { return decl{"border-right", v} }
func borderStyle(v string) decl             { return decl{"border-style", v} }
func borderTop(v string) decl               { return decl{"border-top", v} }
func borderTopColor(v string) decl          { return decl{"border-top-color", v} }
func borderWidth(v string) decl             { return decl{"border-width", v} }
func bottom(v string) decl                  { return decl{"bottom", v} }
func boxShadow(v string) decl               { return decl{"box-shadow", v} }
func boxSizing(v string) decl               { return decl{"box-sizing", v} }
func breakInside(v string) decl             { return decl{"break-inside", v} }
func clip(v string) decl                    { return decl{"clip", v} }
func color(v string) decl                   { return decl{"color", v} }
func colorScheme(v string) decl             { return decl{"color-scheme", v} }
func content(v string) decl                 { return decl{"content", v} }
func cursor(v string) decl                  { return decl{"cursor", v} }
func display(v string) decl                 { return decl{"display", v} }
func fill(v string) decl                    { return decl{"fill", v} }
func filter(v string) decl                  { return decl{"filter", v} }
func flex(v string) decl                    { return decl{"flex", v} }
func flexBasis(v string) decl               { return decl{"flex-basis", v} }
func flexDirection(v string) decl           { return decl{"flex-direction", v} }
func flexShrink(v string) decl              { return decl{"flex-shrink", v} }
func flexWrap(v string) decl                { return decl{"flex-wrap", v} }
func font(v string) decl                    { return decl{"font", v} }
func fontFamily(v string) decl              { return decl{"font-family", v} }
func fontFeatureSettings(v string) decl     { return decl{"font-feature-settings", v} }
func fontSize(v string) decl                { return decl{"font-size", v} }
func fontStyle(v string) decl               { return decl{"font-style", v} }
func fontVariantNumeric(v string) decl      { return decl{"font-variant-numeric", v} }
func fontWeight(v string) decl              { return decl{"font-weight", v} }
func gap(v string) decl                     { return decl{"gap", v} }
func gridArea(v string) decl                { return decl{"grid-area", v} }
func gridAutoRows(v string) decl            { return decl{"grid-auto-rows", v} }
func gridColumn(v string) decl              { return decl{"grid-column", v} }
func gridRow(v string) decl                 { return decl{"grid-row", v} }
func gridTemplateColumns(v string) decl     { return decl{"grid-template-columns", v} }
func gridTemplateRows(v string) decl        { return decl{"grid-template-rows", v} }
func height(v string) decl                  { return decl{"height", v} }
func inset(v string) decl                   { return decl{"inset", v} }
func justifyContent(v string) decl          { return decl{"justify-content", v} }
func justifyItems(v string) decl            { return decl{"justify-items", v} }
func justifySelf(v string) decl             { return decl{"justify-self", v} }
func left(v string) decl                    { return decl{"left", v} }
func letterSpacing(v string) decl           { return decl{"letter-spacing", v} }
func lineHeight(v string) decl              { return decl{"line-height", v} }
func listStyle(v string) decl               { return decl{"list-style", v} }
func margin(v string) decl                  { return decl{"margin", v} }
func marginBottom(v string) decl            { return decl{"margin-bottom", v} }
func marginInline(v string) decl            { return decl{"margin-inline", v} }
func marginLeft(v string) decl              { return decl{"margin-left", v} }
func marginRight(v string) decl             { return decl{"margin-right", v} }
func marginTop(v string) decl               { return decl{"margin-top", v} }
func maxHeight(v string) decl               { return decl{"max-height", v} }
func maxWidth(v string) decl                { return decl{"max-width", v} }
func minHeight(v string) decl               { return decl{"min-height", v} }
func minWidth(v string) decl                { return decl{"min-width", v} }
func opacity(v string) decl                 { return decl{"opacity", v} }
func order(v string) decl                   { return decl{"order", v} }
func outline(v string) decl                 { return decl{"outline", v} }
func outlineOffset(v string) decl           { return decl{"outline-offset", v} }
func overflow(v string) decl                { return decl{"overflow", v} }
func overflowAnchor(v string) decl          { return decl{"overflow-anchor", v} }
func overflowWrap(v string) decl            { return decl{"overflow-wrap", v} }
func overflowX(v string) decl               { return decl{"overflow-x", v} }
func overflowY(v string) decl               { return decl{"overflow-y", v} }
func padding(v string) decl                 { return decl{"padding", v} }
func paddingBottom(v string) decl           { return decl{"padding-bottom", v} }
func paddingLeft(v string) decl             { return decl{"padding-left", v} }
func paddingRight(v string) decl            { return decl{"padding-right", v} }
func paddingTop(v string) decl              { return decl{"padding-top", v} }
func pageBreakInside(v string) decl         { return decl{"page-break-inside", v} }
func perspective(v string) decl             { return decl{"perspective", v} }
func placeItems(v string) decl              { return decl{"place-items", v} }
func pointerEvents(v string) decl           { return decl{"pointer-events", v} }
func position(v string) decl                { return decl{"position", v} }
func right(v string) decl                   { return decl{"right", v} }
func rowGap(v string) decl                  { return decl{"row-gap", v} }
func scrollBehavior(v string) decl          { return decl{"scroll-behavior", v} }
func scrollbarColor(v string) decl          { return decl{"scrollbar-color", v} }
func scrollbarWidth(v string) decl          { return decl{"scrollbar-width", v} }
func stroke(v string) decl                  { return decl{"stroke", v} }
func strokeDasharray(v string) decl         { return decl{"stroke-dasharray", v} }
func strokeDashoffset(v string) decl        { return decl{"stroke-dashoffset", v} }
func strokeLinecap(v string) decl           { return decl{"stroke-linecap", v} }
func strokeWidth(v string) decl             { return decl{"stroke-width", v} }
func tableLayout(v string) decl             { return decl{"table-layout", v} }
func textAlign(v string) decl               { return decl{"text-align", v} }
func textDecoration(v string) decl          { return decl{"text-decoration", v} }
func textDecorationThickness(v string) decl { return decl{"text-decoration-thickness", v} }
func textOverflow(v string) decl            { return decl{"text-overflow", v} }
func textTransform(v string) decl           { return decl{"text-transform", v} }
func textUnderlineOffset(v string) decl     { return decl{"text-underline-offset", v} }
func top(v string) decl                     { return decl{"top", v} }
func transform(v string) decl               { return decl{"transform", v} }
func transformOrigin(v string) decl         { return decl{"transform-origin", v} }
func transformStyle(v string) decl          { return decl{"transform-style", v} }
func transition(v string) decl              { return decl{"transition", v} }
func transitionDuration(v string) decl      { return decl{"transition-duration", v} }
func verticalAlign(v string) decl           { return decl{"vertical-align", v} }
func viewTransitionName(v string) decl      { return decl{"view-transition-name", v} }
func whiteSpace(v string) decl              { return decl{"white-space", v} }
func width(v string) decl                   { return decl{"width", v} }
func willChange(v string) decl              { return decl{"will-change", v} }
func wordWrap(v string) decl                { return decl{"word-wrap", v} }
func zIndex(v string) decl                  { return decl{"z-index", v} }
func zoom(v string) decl                    { return decl{"zoom", v} }
