import { chromium } from 'playwright';
const BASE='http://127.0.0.1:8099';
const log=[];const P=s=>log.push('PASS '+s);const F=s=>log.push('FAIL '+s);
const active=p=>p.evaluate(()=>{const a=document.activeElement;
  if(a&&a.classList.contains('add-btn'))return 'trigger';
  if(a&&a.getAttribute('role')==='menuitem'){const items=[...a.closest('.add-wrap').querySelectorAll('[role="menuitem"]')];return 'item#'+items.indexOf(a);}
  return 'other:'+(a?a.tagName:'none');});
(async()=>{const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1280,height:900}});const p=await ctx.newPage();
await p.goto(BASE,{waitUntil:'domcontentloaded'});
await p.waitForFunction(()=>document.querySelector('#app')?.textContent.length>40,{timeout:20000});
await p.evaluate(()=>{const o=document.getElementById('gwc-error-overlay');if(o)o.remove();});await p.waitForTimeout(500);
await p.click('.add-btn'); await p.waitForTimeout(300);
const n=await p.evaluate(()=>document.querySelectorAll('.add-wrap [role="menuitem"]').length);
log.push('INFO opened; menuitems='+n+', active='+await active(p));
await p.keyboard.press('ArrowDown'); await p.waitForTimeout(100);
((await active(p))==='item#0')?P('ArrowDown from trigger → first item'):F('ArrowDown→first: '+await active(p));
await p.keyboard.press('ArrowDown'); await p.waitForTimeout(100);
((await active(p))==='item#1')?P('ArrowDown → item#1'):F('item#1: '+await active(p));
await p.keyboard.press('End'); await p.waitForTimeout(100);
((await active(p))==='item#'+(n-1))?P('End → last item#'+(n-1)):F('End: '+await active(p));
await p.keyboard.press('Home'); await p.waitForTimeout(100);
((await active(p))==='item#0')?P('Home → first item'):F('Home: '+await active(p));
await p.keyboard.press('ArrowUp'); await p.waitForTimeout(100);
((await active(p))==='item#'+(n-1))?P('ArrowUp from first wraps to last'):F('wrap: '+await active(p));
await p.keyboard.press('Escape'); await p.waitForTimeout(200);
((await active(p))==='trigger' && await p.evaluate(()=>document.querySelector('.add-menu').className.includes('hidden-menu')))?P('Escape closes + refocus trigger'):F('escape: '+await active(p));
console.log(log.map(s=>'  '+s).join('\n'));
const f=log.filter(s=>s.startsWith('FAIL')).length;
console.log(`\n${log.filter(s=>s.startsWith('PASS')).length} PASS / ${f} FAIL`);
await b.close(); process.exit(f?1:0);})();
