// SPDX-License-Identifier: MIT

// Package txnprov answers "who decided this transaction's category, and how much
// should I trust it?" for one row of the ledger.
//
// A ledger row shows a category and nothing about where it came from. A category a
// person chose, a category a rule wrote, and a category an import guessed all
// render identically — so the user has no way to tell a settled decision from a
// machine's suggestion, and reviewing the file means re-checking everything or
// trusting everything (C579).
//
// The classification is DERIVED, not stored. Nothing on the transaction records
// which rule filed it, and back-filling that field for existing data would be a
// guess dressed as a fact. What can be established honestly is:
//
//   - whether a person confirmed the row (Transaction.Reviewed, set on deliberate
//     entry and by the review queue),
//   - how the row entered the ledger (Transaction.Source),
//   - whether a rule that exists NOW would file it where it currently sits.
//
// The last one is the useful signal and also the one to be careful about: a rule
// agreeing with the current category is evidence the category is automatic, not
// proof. The wording the UI uses reflects that — it names the rule and says the
// category matches it, rather than asserting the rule wrote it.
//
// Pure (no syscall/js) and unit-tested on native Go.
package txnprov

import (
	"github.com/monstercameron/CashFlux/internal/domain"
	"github.com/monstercameron/CashFlux/internal/rules"
)

// Level is how much a row's category has been vouched for.
type Level int

const (
	// None means the row carries no category at all. It is not a trust level so
	// much as the absence of a decision, and the ledger already marks it.
	None Level = iota
	// Automatic means the category was assigned without a person confirming it —
	// by an import, a recurring schedule, the assistant, or a rule.
	Automatic
	// Confirmed means a person put the category there or explicitly accepted it.
	Confirmed
)

// Provenance is the full answer for one row: the trust level, and the rule that
// accounts for the category when one does.
type Provenance struct {
	Level Level
	// RuleMatch is the first rule that both matches this transaction and files it
	// under the category it currently carries — the rule a user would have to change
	// to change this row's fate. Nil when no rule explains the category, including
	// for every Confirmed row (a confirmed decision is the user's, whatever a rule
	// would have done).
	RuleMatch *rules.Rule
}

// Automatic reports whether the row's category came from automation and is
// unconfirmed — the case worth marking in the UI.
func (p Provenance) IsAutomatic() bool { return p.Level == Automatic }

// Of classifies one transaction against the CURRENT rule set.
//
// Order matters and encodes the trust model:
//
//  1. No category — nothing to attribute.
//  2. A transfer leg — it has no category by design; attributing one would invent
//     a decision nobody made.
//  3. Reviewed — a person accepted this row. That outranks any rule: the whole
//     point of confirming is that the decision stops being the machine's.
//  4. Entered by hand — the person who typed the row chose the category. Manual
//     entry IS the confirmation for this purpose.
//  5. Everything else — imported, scanned, generated by a schedule, or written by
//     the assistant — is automatic, whether or not a rule explains it.
func Of(t domain.Transaction, rs []rules.Rule) Provenance {
	if t.CategoryID == "" || t.IsTransfer() {
		return Provenance{Level: None}
	}
	if t.Reviewed || t.Source == domain.TxnSourceManual {
		return Provenance{Level: Confirmed}
	}
	return Provenance{Level: Automatic, RuleMatch: explainingRule(t, rs)}
}

// explainingRule finds the first rule that matches t AND files it under the
// category t already carries.
//
// The second half is load-bearing. Taking merely the first MATCHING rule would
// name a rule that sets tags, or renames the payee, or files the row somewhere
// else entirely — and telling a user "this came from rule X" when X would have put
// it elsewhere is a worse lie than saying nothing. Returning nil is the honest
// answer for "automatic, but no current rule accounts for it" (an old import, or a
// rule that has since been edited).
func explainingRule(t domain.Transaction, rs []rules.Rule) *rules.Rule {
	return rules.FirstMatchFullWhere(
		rs, t.Payee, t.Desc, t.Amount.Amount, t.AccountID, rules.NewTxnDate(t.Date),
		func(r rules.Rule) bool { return r.SetCategoryID == t.CategoryID },
	)
}
